"""Agent 4: Demand forecasting.

Tracks how often each skill is asked for across the postings the system has
seen, then projects that forward. The candidate gets an answer to a question a
job board cannot give them: not what is being asked for today, but what is
being asked for more often than it was a month ago.

A deliberate contrast with the healthcare forecasting work that preceded this
project. There, quarterly occupancy returns were forecast at monthly frequency
with yearly seasonality enabled, which left eight unconstrained months a year
and produced predictions that had to be clipped before they reached the screen.
Here the observation frequency and the forecast frequency are the same, weekly,
because the counts are generated by the ingestion agent's own weekly run. The
mismatch that caused that failure cannot arise.

Prophet needs a reasonable history before it says anything useful. Below that
threshold the agent reports insufficient history rather than fitting a model to
three points and presenting the result as a forecast.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import UTC, date, datetime, timedelta
from enum import Enum

from agents.extraction import Confidence, Requirements

logger = logging.getLogger(__name__)

# Prophet is imported lazily. It is a heavy dependency with a compiled backend,
# and the counting and trend logic below is worth testing without it.
_PROPHET_IMPORT_ERROR: str | None = None

# Minimum weekly observations before a forecast is attempted. Below this the
# agent says so rather than extrapolating from noise.
MIN_WEEKS_FOR_FORECAST = 8

# Weeks averaged to form the current baseline a forecast is compared against.
BASELINE_WEEKS = 3

# Reconstructed history must rest on at least this many real postings before a
# share trend is reported. Roughly three postings a week across eight weeks.
MIN_BOOTSTRAP_POSTINGS = 24

# Percentage point move that counts as a genuine shift in a share series.
SHARE_TREND_POINTS = 3.0

# If at least this fraction of trending skills move the same way, the report
# is flagged as likely reflecting the data rather than the market.
UNIFORM_MOVEMENT_THRESHOLD = 0.85
UNIFORM_MOVEMENT_MIN_SKILLS = 5

# A skill must be projected to reach at least this rate before emerging from a
# zero baseline counts as rising rather than noise.
MIN_EMERGING_RATE = 2.0

# A skill must appear this many times in total to be worth modelling at all.
MIN_TOTAL_MENTIONS = 5

# Percentage change over the forecast horizon that counts as a real move
# rather than week to week noise.
TREND_THRESHOLD_PCT = 10.0


class Trend(str, Enum):
    RISING = "rising"
    STABLE = "stable"
    FALLING = "falling"
    INSUFFICIENT_HISTORY = "insufficient_history"


@dataclass
class SkillDemand:
    skill: str
    total_mentions: int
    weeks_observed: int
    current_weekly_rate: float
    trend: Trend
    # Populated only when a model was actually fitted.
    forecast_weekly_rate: float | None = None
    change_pct: float | None = None
    # Absolute move. For shares this is percentage points, the honest measure:
    # three percent to seven point six percent is plus four point six points,
    # which "+155%" dramatically overstates.
    change_points: float | None = None
    note: str = ""
    # Which engine produced the projection, so a degraded run is visible in
    # the output rather than silently passing as a Prophet forecast.
    method: str = "prophet"

    @property
    def is_forecast(self) -> bool:
        return self.forecast_weekly_rate is not None


@dataclass
class DemandReport:
    generated_for_week: date
    skills: list[SkillDemand] = field(default_factory=list)
    # Snapshot history counts postings per week. Reconstructed history records
    # the percentage of postings mentioning a skill. The two must be labelled
    # differently or a share of 12 percent reads as twelve postings a week.
    rate_unit: str = "per week"

    def rising(self, limit: int = 10) -> list[SkillDemand]:
        movers = [s for s in self.skills if s.trend is Trend.RISING]
        return sorted(movers, key=lambda s: s.change_pct or 0, reverse=True)[:limit]

    def falling(self, limit: int = 10) -> list[SkillDemand]:
        movers = [s for s in self.skills if s.trend is Trend.FALLING]
        return sorted(movers, key=lambda s: s.change_pct or 0)[:limit]

    def most_demanded(self, limit: int = 15) -> list[SkillDemand]:
        return sorted(self.skills, key=lambda s: s.total_mentions, reverse=True)[:limit]

    @property
    def uniform_movement(self) -> Trend | None:
        """Return a direction if nearly every forecast skill shares it.

        Genuine markets do not move every skill the same way at once. When they
        appear to, the cause is almost always in the data rather than the
        market: a shift in how complete the postings were, a change in which
        sources responded, or a stale week pulling the fit. Two consecutive
        live runs showed every major skill falling and then every one rising,
        and this check would have flagged both.
        """
        called = [s for s in self.skills if s.trend in (Trend.RISING, Trend.FALLING)]
        if len(called) < UNIFORM_MOVEMENT_MIN_SKILLS:
            return None
        rising = sum(1 for s in called if s.trend is Trend.RISING)
        share_rising = rising / len(called)
        if share_rising >= UNIFORM_MOVEMENT_THRESHOLD:
            return Trend.RISING
        if share_rising <= 1 - UNIFORM_MOVEMENT_THRESHOLD:
            return Trend.FALLING
        return None


# ---------------------------------------------------------------------------
# Counting
# ---------------------------------------------------------------------------


def today() -> date:
    """Timezone aware current date.

    UK postings and a UK candidate, but pinning to UTC keeps the weekly
    buckets stable regardless of where the job happens to run.
    """
    return datetime.now(UTC).date()


def week_starting(day: date) -> date:
    """Normalise a date to the Monday of its week."""
    return day - timedelta(days=day.weekday())


def count_weekly_mentions(
    snapshots: list[tuple[date, list[Requirements]]],
) -> dict[str, dict[date, int]]:
    """Build per skill weekly counts from dated extraction snapshots.

    Each snapshot is one ingestion run. Counting the number of postings that
    mention a skill, rather than the number of mentions, prevents a single
    verbose posting that repeats "Python" twelve times from distorting the week.
    """
    counts: dict[str, dict[date, int]] = defaultdict(lambda: defaultdict(int))

    for run_date, requirements in snapshots:
        week = week_starting(run_date)
        for requirement in requirements:
            # A set, so one posting contributes at most one to each skill.
            for skill in set(requirement.skill_names):
                counts[skill][week] += 1

    return {skill: dict(weeks) for skill, weeks in counts.items()}


def fill_missing_weeks(series: dict[date, int]) -> dict[date, int]:
    """Insert explicit zeros for weeks with no mentions.

    A skill that disappears for three weeks has genuinely fallen in demand.
    Leaving those weeks absent would let Prophet interpolate straight through
    the gap and miss the decline entirely.
    """
    if not series:
        return {}

    start, end = min(series), max(series)
    filled: dict[date, int] = {}
    cursor = start
    while cursor <= end:
        filled[cursor] = series.get(cursor, 0)
        cursor += timedelta(weeks=1)
    return filled


# ---------------------------------------------------------------------------
# Forecasting
# ---------------------------------------------------------------------------


def _load_prophet():
    global _PROPHET_IMPORT_ERROR
    try:
        from prophet import Prophet
    except ImportError as exc:  # pragma: no cover - environment dependent
        _PROPHET_IMPORT_ERROR = str(exc)
        return None
    return Prophet


def classify_share_trend(current: float, predicted: float) -> tuple[Trend, float]:
    """Classify a share series by its move in percentage points.

    A relative threshold is wrong for shares. On a small base a single extra
    posting clears any percentage threshold, which is how one posting a week
    became "+155%". Requiring a move of a few points means the change has to
    reflect more than one listing.
    """
    points = predicted - current
    if points >= SHARE_TREND_POINTS:
        return Trend.RISING, points
    if points <= -SHARE_TREND_POINTS:
        return Trend.FALLING, points
    return Trend.STABLE, points


def classify_trend(current: float, predicted: float) -> tuple[Trend, float]:
    """Compare a predicted rate against the current one.

    The threshold exists because a weekly count moving from 4 to 5 is noise,
    not a signal, and labelling it as growth would make every skill look like
    it is moving.
    """
    if current <= 0:
        # Growth from zero has no meaningful percentage. Reporting "+100%" here
        # was how a skill with no recent mentions appeared at the top of the
        # rising list. A skill emerging from nothing is noted without a figure.
        return (Trend.RISING, 0.0) if predicted >= MIN_EMERGING_RATE else (Trend.STABLE, 0.0)

    change = ((predicted - current) / current) * 100
    if change >= TREND_THRESHOLD_PCT:
        return Trend.RISING, change
    if change <= -TREND_THRESHOLD_PCT:
        return Trend.FALLING, change
    return Trend.STABLE, change


def _apply_trend(base: SkillDemand, current: float, predicted: float, share_mode: bool) -> None:
    """Record the projection and classify it with the right measure."""
    points = predicted - current
    if share_mode:
        trend, _ = classify_share_trend(current, predicted)
    else:
        trend, _ = classify_trend(current, predicted)
    _, relative = classify_trend(current, predicted)
    base.forecast_weekly_rate = round(predicted, 2)
    base.change_pct = round(relative, 1)
    base.change_points = round(points, 1)
    base.trend = trend


def _least_squares_projection(filled: dict[date, int], horizon_weeks: int) -> float:
    """Project the series forward with an ordinary least squares line.

    Used when Prophet is not installed. On a couple of months of weekly points
    there is no seasonality to discover, so a straight line is close to what
    Prophet would produce anyway. Prophet earns its place on longer series and
    for its uncertainty intervals, not on eight points.
    """
    weeks = sorted(filled)
    ordered = [float(filled[week]) for week in weeks]
    n = len(ordered)
    # Elapsed weeks from the first observation, not list position. With
    # reconstructed history the observations are not evenly spaced, and using
    # positions made a January week sit beside a July one as if they were
    # consecutive, turning the gap between them into a steep weekly slide.
    first = weeks[0]
    xs = [(week - first).days / 7 for week in weeks]
    mean_x = sum(xs) / n
    mean_y = sum(ordered) / n
    denominator = sum((x - mean_x) ** 2 for x in xs)
    if denominator == 0:
        return mean_y
    slope = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ordered, strict=True)) / denominator
    intercept = mean_y - slope * mean_x
    return max(0.0, intercept + slope * (xs[-1] + horizon_weeks))


def forecast_skill(
    skill: str,
    series: dict[date, int],
    horizon_weeks: int = 4,
    prophet_cls=None,
    zero_fill: bool = True,
    raw_total: int | None = None,
    share_mode: bool = False,
) -> SkillDemand:
    """Forecast one skill's weekly demand.

    Returns an honest result when there is not enough history, rather than
    fitting a model to a handful of points and presenting it as a prediction.
    """
    # Zero filling is right for recorded snapshots, where a skill absent from a
    # real weekly run genuinely had no demand. It is wrong for reconstructed
    # history, where a missing week means too few postings to measure, and
    # filling it with zero would turn "unknown" into "no demand at all".
    filled = fill_missing_weeks(series) if zero_fill else dict(sorted(series.items()))
    total = sum(filled.values())
    weeks = len(filled)

    # A trailing mean rather than the single latest week. One quiet week should
    # not decide whether a skill is rising, and the latest point is the one most
    # likely to be incomplete.
    recent = [filled[w] for w in sorted(filled)][-BASELINE_WEEKS:]
    current = sum(recent) / len(recent) if recent else 0.0

    base = SkillDemand(
        skill=skill,
        total_mentions=total,
        weeks_observed=weeks,
        current_weekly_rate=float(current),
        trend=Trend.INSUFFICIENT_HISTORY,
    )

    # In share mode the series holds percentages, so summing it says nothing
    # about how many postings sit behind a skill. A skill at three percent for
    # eight weeks sums to twenty four and would sail through a five mention
    # guard while resting on roughly one posting a week. The guard must count
    # postings, and share mode sets a higher bar because a share built on one
    # or two postings a week swings by tens of percent on a single listing.
    postings_behind = raw_total if raw_total is not None else total
    minimum = MIN_BOOTSTRAP_POSTINGS if share_mode else MIN_TOTAL_MENTIONS
    base.total_mentions = postings_behind
    if postings_behind < minimum:
        base.note = f"only {postings_behind} postings mention it, too few to call a trend"
        return base

    if weeks < MIN_WEEKS_FOR_FORECAST:
        base.note = (
            f"{weeks} weeks of history, {MIN_WEEKS_FOR_FORECAST} needed before forecasting"
        )
        return base

    Prophet = prophet_cls or _load_prophet()
    if Prophet is None:
        # Degrade to a linear trend rather than producing nothing. Prophet is a
        # heavy dependency with a compiled backend and it does not install
        # cleanly everywhere, which must not mean the agent stops working.
        predicted = _least_squares_projection(filled, horizon_weeks)
        _apply_trend(base, current, predicted, share_mode)
        base.method = "linear"
        base.note = f"{weeks} weeks of history, linear trend (prophet not installed)"
        return base

    import pandas as pd

    frame = pd.DataFrame(
        {"ds": list(filled.keys()), "y": [float(v) for v in filled.values()]}
    ).sort_values("ds")

    try:
        # Weekly observations forecast weekly. Yearly seasonality is switched
        # off deliberately: a few months of history cannot support an annual
        # cycle, and asking for one is exactly the mistake that produced
        # unusable occupancy forecasts on the previous project.
        # Prophet defaults to twenty five changepoints, which on eight weekly
        # points is meaningless and triggers a warning per skill. Scaling them
        # to the series keeps the model proportionate to the data it has.
        model = Prophet(
            weekly_seasonality=False,
            yearly_seasonality=False,
            daily_seasonality=False,
            interval_width=0.8,
            n_changepoints=max(1, min(5, len(filled) // 3)),
        )
        model.fit(frame)
        future = model.make_future_dataframe(periods=horizon_weeks, freq="W-MON")
        prediction = model.predict(future)
    except Exception as exc:  # noqa: BLE001
        # Any modelling failure degrades to no forecast rather than no report.
        logger.warning("Forecast failed for %s: %s", skill, exc)
        base.note = f"model fitting failed: {exc}"
        return base

    predicted = float(max(0.0, prediction.iloc[-1]["yhat"]))
    _apply_trend(base, current, predicted, share_mode)
    base.method = "prophet"
    base.note = f"{weeks} weeks of history"
    return base


# ---------------------------------------------------------------------------
# Agent entry point
# ---------------------------------------------------------------------------


def build_report_from_series(
    series: dict[str, dict[date, int]],
    horizon_weeks: int = 4,
    prophet_cls=None,
    zero_fill: bool = True,
    rate_unit: str = "per week",
    raw_totals: dict[str, int] | None = None,
) -> DemandReport:
    """Build a report from per skill date series.

    This is the path the pipeline uses, because history is stored as counts
    rather than as full extraction results.
    """
    latest = max(
        (d for weeks in series.values() for d in weeks),
        default=today(),
    )
    share_mode = rate_unit.startswith("%")
    results = [
        forecast_skill(
            skill, weeks, horizon_weeks, prophet_cls,
            zero_fill=zero_fill,
            raw_total=(raw_totals or {}).get(skill),
            share_mode=share_mode,
        )
        for skill, weeks in series.items()
    ]

    modelled = sum(1 for r in results if r.is_forecast)
    logger.info(
        "Demand report across %d skills. %d forecast, %d lack sufficient history.",
        len(results), modelled, len(results) - modelled,
    )
    return DemandReport(
        generated_for_week=week_starting(latest), skills=results, rate_unit=rate_unit
    )


def build_report(
    snapshots: list[tuple[date, list[Requirements]]],
    horizon_weeks: int = 4,
    prophet_cls=None,
) -> DemandReport:
    """Produce a demand report across every skill seen.

    Out of domain postings are expected to have been filtered out already by
    the extraction agent, but they are harmless here either way, since a
    marketing role contributes no taxonomy skills to count.
    """
    counts = count_weekly_mentions(snapshots)
    latest = max((d for d, _ in snapshots), default=today())

    results = [
        forecast_skill(skill, series, horizon_weeks, prophet_cls)
        for skill, series in counts.items()
    ]

    modelled = sum(1 for r in results if r.is_forecast)
    logger.info(
        "Demand report across %d skills. %d forecast, %d lack sufficient history.",
        len(results), modelled, len(results) - modelled,
    )

    return DemandReport(generated_for_week=week_starting(latest), skills=results)


# ---------------------------------------------------------------------------
# Bootstrapping history from posting dates
# ---------------------------------------------------------------------------

# A reconstructed week needs at least this many postings before its share is
# trustworthy. Two postings in a week makes every skill either 0% or 50%.
MIN_POSTINGS_PER_WEEK = 8

# Reconstruction only looks this far back. Postings still listed months after
# publication are not a random sample of their week: they are disproportionately
# the roles nobody could fill, which skew specialist and senior. Share corrects
# for how many postings survive, but not for which ones, so old weeks carry a
# different skill mix and would drag every trend line toward them.
MAX_BOOTSTRAP_WEEKS = 12


def bootstrap_series_from_posting_dates(
    requirements: list[Requirements],
    posting_dates: dict[str, date | None],
    raw_totals: dict[str, int] | None = None,
) -> dict[str, dict[date, int]]:
    """Reconstruct weekly history from the dates postings were published.

    A new deployment has no accumulated snapshots, so nothing can be forecast
    until it has run weekly for a month or more. Posting dates are already
    collected during ingestion, and job boards carry roughly the last one to
    two months, so a single run yields several weeks of history immediately.

    This carries an artefact that has to be corrected for. Older postings get
    filled and delisted, so the number of surviving postings from a given week
    falls the further back you look. Counting mentions per week would therefore
    show every skill rising toward the present, in every run, regardless of
    what the market is doing.

    The correction is to record the share of that week's postings mentioning
    each skill, scaled to a per hundred rate, rather than the raw count. Share
    is unaffected by how many postings from a week are still listed. The value
    returned is an integer rate per hundred postings, so it slots into the same
    series shape the snapshot path produces.

    The reconstruction is still weaker than accumulated snapshots, because a
    delisted posting may not be a random sample of its week. It is a starting
    point that is replaced by real history as snapshots accumulate.
    """
    postings_per_week: dict[date, int] = defaultdict(int)
    mentions_per_week: dict[str, dict[date, int]] = defaultdict(lambda: defaultdict(int))

    # Only fully described postings go into the share. An Adzuna excerpt yields
    # one or two skills where a full Reed description yields eight or ten, so
    # if the mix of the two shifts from week to week, every skill's share rises
    # or falls together for reasons that have nothing to do with the market.
    # One live run showed every major skill falling and the next showed them
    # all rising, which is the signature of a moving denominator rather than a
    # moving market.
    full_only = [r for r in requirements if r.confidence is Confidence.FULL]
    excluded = len(requirements) - len(full_only)
    if excluded:
        logger.info(
            "Excluded %d excerpt only postings from the share calculation, since "
            "they cannot show every skill a role asks for.",
            excluded,
        )

    for requirement in full_only:
        posted = posting_dates.get(requirement.posting_id)
        if posted is None:
            continue
        week = week_starting(posted)
        postings_per_week[week] += 1
        for skill in set(requirement.skill_names):
            mentions_per_week[skill][week] += 1

    # The current week is still in progress, so most skills have not appeared
    # in it yet. Treating it as a finished week made almost every skill look
    # as though it had collapsed to zero in the latest period.
    in_progress = week_starting(today())
    oldest_allowed = in_progress - timedelta(weeks=MAX_BOOTSTRAP_WEEKS)

    stale = {week for week in postings_per_week if week < oldest_allowed}
    if stale:
        logger.info(
            "Ignored %d week(s) older than %d weeks. Postings that survive that long "
            "are a biased sample of their week.",
            len(stale), MAX_BOOTSTRAP_WEEKS,
        )

    usable_weeks = {
        week for week, total in postings_per_week.items()
        if total >= MIN_POSTINGS_PER_WEEK
        and week != in_progress
        and week >= oldest_allowed
    }
    thin = len(postings_per_week) - len(usable_weeks)
    if thin:
        logger.info(
            "Dropped %d week(s) with fewer than %d postings, too thin for a reliable share.",
            thin, MIN_POSTINGS_PER_WEEK,
        )

    series: dict[str, dict[date, int]] = {}
    for skill, weeks in mentions_per_week.items():
        rates: dict[date, int] = {}
        for week in usable_weeks:
            total = postings_per_week[week]
            rates[week] = round(weeks.get(week, 0) / total * 100)
        if rates:
            series[skill] = rates
            if raw_totals is not None:
                # The real number of postings behind this skill, as opposed to
                # the sum of its percentage shares.
                raw_totals[skill] = sum(weeks.get(week, 0) for week in usable_weeks)

    if series:
        span = sorted(usable_weeks)
        logger.info(
            "Bootstrapped %d skills across %d weeks (%s to %s) from posting dates. "
            "Values are share per hundred postings, not raw counts.",
            len(series), len(span), span[0], span[-1],
        )
    return series


def build_bootstrap_report(
    requirements: list[Requirements],
    posting_dates: dict[str, date | None],
    horizon_weeks: int = 4,
    prophet_cls=None,
) -> DemandReport:
    """Demand report built from reconstructed history rather than snapshots."""
    raw_totals: dict[str, int] = {}
    series = bootstrap_series_from_posting_dates(requirements, posting_dates, raw_totals)
    return build_report_from_series(
        series, horizon_weeks, prophet_cls,
        zero_fill=False, rate_unit="% of postings", raw_totals=raw_totals,
    )
